# Generated by Django 4.1.5 on 2023-02-07 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('private_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('price', models.CharField(max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('category_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('mainImage', models.ImageField(upload_to='static/listing_images/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='static/listing_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='static/listing_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='static/listing_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='static/listing_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='static/listing_images/')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('features', models.CharField(max_length=10000)),
                ('rating', models.CharField(default='0', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nairobi_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('rating', models.CharField(default='0', max_length=100)),
                ('image', models.ImageField(default='static/user_images/default_img.jpg', upload_to='static/user_images/')),
                ('private_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('features', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_by', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=10000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(max_length=100)),
                ('user_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nairobi_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='ListingReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=10000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(max_length=100)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nairobi_app.listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nairobi_app.user'),
        ),
    ]
