# Generated by Django 4.1.5 on 2023-02-11 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nairobi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nairobi_app.userpackage'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
