# Generated by Django 4.1.5 on 2023-01-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nairobi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='private_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='public_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='user_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='private_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='public_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='image1',
            field=models.ImageField(upload_to='listing_images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image2',
            field=models.ImageField(upload_to='listing_images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image3',
            field=models.ImageField(upload_to='listing_images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image4',
            field=models.ImageField(upload_to='listing_images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image5',
            field=models.ImageField(upload_to='listing_images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='mainImage',
            field=models.ImageField(upload_to='listing_images/'),
        ),
    ]
