# Generated by Django 4.1.5 on 2023-02-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nairobi_app', '0002_user_description_user_package_alter_listing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category_name',
        ),
        migrations.AddField(
            model_name='listing',
            name='video_360_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
