# Generated by Django 4.1.5 on 2023-02-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nairobi_app', '0003_remove_listing_category_name_listing_video_360_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
