# Generated by Django 4.1.5 on 2023-01-26 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nairobi_app', '0003_listing_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreviews',
            name='user',
        ),
        migrations.AddField(
            model_name='listing',
            name='category_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='user_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingreviews',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreviews',
            name='user_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreviews',
            name='user_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Nairobi_app.user'),
            preserve_default=False,
        ),
    ]
