# Generated by Django 4.1.5 on 2023-01-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nairobi_app', '0004_remove_userreviews_user_listing_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user_images/default_img.jpg', upload_to='user_images/'),
        ),
    ]
