# Generated by Django 4.1.5 on 2023-02-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nairobi_app', '0005_remove_listing_features_listing_feature1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='package',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
