# Generated by Django 4.1.5 on 2023-02-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nairobi_app', '0006_alter_user_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
