# Generated by Django 4.1.5 on 2023-02-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nairobi_app', '0007_delete_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ad_count',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
