# Generated by Django 4.1.6 on 2023-02-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nairobi_app', '0009_user_facebook_user_instagram_user_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingreviews',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreviews',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
