# Generated by Django 4.1.6 on 2023-02-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nairobi_app', '0010_listingreviews_subject_userreviews_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='mainImage',
            new_name='main_image',
        ),
    ]
