# Generated by Django 4.1.6 on 2023-02-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nairobi_app', '0011_rename_mainimage_listing_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rating',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
