# Generated by Django 4.1.6 on 2023-02-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nairobi_app', '0012_alter_listing_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='google_map_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
