# Generated by Django 4.1.6 on 2023-03-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nairobi_app', '0014_listing_active_alter_listing_google_map_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='username',
        ),
    ]
